PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://fr.dbpedia.org/page/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
	?URI owl:sameAs ?country;
		dbpedia:Year ?Year;
		dbpedia:Life_expectancy ?Life_expectancy;
		dbpedia:Total_fertility_rate ?Total_fertility_rate;
		dbpedia:Cardiovascular_disease ?Cardiovascular_disease;
		dbpedia:Cancer ?Cancer;
		dbpedia:Respiratory_disease ?Respiratory_disease;
		dbpedia:Diabetes_mellitus ?Diabetes;
		dbpedia:Dementia ?Dementia;
		dbpedia:Respiratory_tract_infection ?Respiratory_tract_infection;
		dbpedia:Infant_mortality ?Infant_mortality;
		dbpedia:Lower_respiratory_infections ?Lower_respiratory_infections;
		dbpedia:Diarrhea ?Diarrhea;
		dbpedia:Traffic_collision ?Traffic_collision;
		dbpedia:Liver ?Liver;
		dbpedia:Tuberculosis ?Tuberculosis;
		dbpedia:Kidney_disease ?Kidney_disease;
		dbpedia:Gastrointestinal_disease ?Gastrointestinal_disease;
		dbpedia:HIV ?HIV;
		dbpedia:Suicide ?Suicide;
		dbpedia:Malaria ?Malaria;
		dbpedia:Homicide ?Homicide;
		dbpedia:Malnutrition ?Malnutrition;
		dbpedia:Meningitis ?Meningitis;
		dbpedia:Protein-energy_malnutrition ?Protein_energy_malnutrition;
		dbpedia:Drowning ?Drowning;
		dbpedia:Maternal_death ?Maternal_death;
		dbpedia:Parkinsonism ?Parkinsonism;
		dbpedia:Alcohol ?Alcohol;
		dbpedia:Drug ?Drug;
		dbpedia:Hepatitis ?Hepatitis;
		dbpedia:Fire ?Fire;
		dbpedia:Heat ?Heat;
		dbpedia:Natural_disaster ?Natural_disaster;
		dbpedia:Conflict ?Conflict;
		dbpedia:Terrorism ?Terrorism;
	  }
  FROM <file:dataset.csv>
  WHERE {
	BIND (URI(CONCAT('http://dbpedia.org/page/', ?country)) AS ?URI)
	BIND (xsd:decimal(?life_expectancy) AS ?Life_expectancy)
	BIND (xsd:decimal(?total_fertility_rate) AS ?Total_fertility_rate)
	BIND (xsd:decimal(?factorname1) AS ?Cardiovascular_disease)
	BIND (xsd:decimal(?factorname2) AS ?Cancer)
	BIND (xsd:decimal(?factorname32) AS ?Lower_respiratory_infections)
	BIND (xsd:decimal(?factorname4) AS ?Diabetes_mellitus)
	BIND (xsd:decimal(?factorname5) AS ?Dementia)
	BIND (xsd:decimal(?factorname6) AS ?Respiratory_tract_infection)
	BIND (xsd:decimal(?factorname7) AS ?Infant_mortality)
	BIND (xsd:decimal(?factorname8) AS ?Diarrhea)
	BIND (xsd:decimal(?factorname9) AS ?Traffic_collision)
	BIND (xsd:decimal(?factorname10) AS ?Liver)
	BIND (xsd:decimal(?factorname11) AS ?Tuberculosis)
	BIND (xsd:decimal(?factorname12) AS ?Kidney_disease)
	BIND (xsd:decimal(?factorname13) AS ?Gastrointestinal_disease)
	BIND (xsd:decimal(?factorname14) AS ?HIV_AIDS)
	BIND (xsd:decimal(?factorname15) AS ?Suicide)
	BIND (xsd:decimal(?factorname16) AS ?Malaria)
	BIND (xsd:decimal(?factorname17) AS ?Homicide)
	BIND (xsd:decimal(?factorname18) AS ?Malnutrition)
	BIND (xsd:decimal(?factorname19) AS ?Meningitis)
	BIND (xsd:decimal(?factorname20) AS ?Protein_energy_malnutrition)
	BIND (xsd:decimal(?factorname21) AS ?Drowning)
	BIND (xsd:decimal(?factorname22) AS ?Maternal_death)
	BIND (xsd:decimal(?factorname23) AS ?Parkinsons_disease)
	BIND (xsd:decimal(?factorname24) AS ?Alcohol)
	BIND (xsd:decimal(?factorname25) AS ?Drug)
	BIND (xsd:decimal(?factorname26) AS ?Hepatitis)
	BIND (xsd:decimal(?factorname27) AS ?Fire)
	BIND (xsd:decimal(?factorname28) AS ?Heat)
	BIND (xsd:decimal(?factorname29) AS ?Natural_disaster)
	BIND (xsd:decimal(?factorname30) AS ?Conflict)
	BIND (xsd:decimal(?terrorism) AS ?Terrorism)	
}