PREFIX dbpedia: <http://fr.dbpedia.org/page/>
PREFIX db: <http://dbpedia.org/ontology/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?Country (SAMPLE(?pop) as ?Pop) (SAMPLE(?year) as ?Year) (SAMPLE(?lex) as ?Lex) (max(?HIV) AS ?maxhiv) 
WHERE{
  ?x
     owl:sameAs ?Country;
     dbpedia:Year ?year;
     dbpedia:HIV ?HIV;
     dbpedia:Life_expectancy ?lex.
   ?y dbo:Country ?Country;
     dbp:populationEstimateYear ?year;
     dbp:populationData ?pop.
  FILTER(xsd:integer(?pop) <= 20000000 && ?lex <= "75")
}
GROUP BY ?Country 
ORDER BY DESC(?maxhiv)
